version: "2"
checks:
  argument-count:
    config:
      threshold: 6
  complex-logic:
    config:
      threshold: 10
  file-lines:
    config:
      threshold: 500
  method-complexity:
    config:
      threshold: 10
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 50
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 10

plugins:
  sonar-python:
    enabled: true
    config:
      tests_patterns:
      - tests/**
  pep8:
    enabled: false
  radon:
    enabled: false

exclude_patterns:
  - "docs/"
  - "tasks/"
  - ".github/"
  - ".pre-commit-config.yml"
  - "*.yml"
  - "*.yaml"
  - "*.rst"
  - "*.ini"
