version: 2
build:
  os: ubuntu-lts-latest
  tools:
    python: "3"
  commands:
    - pip install uv
    - uv venv -p 3.14
    - uv pip install tox-uv tox@.
    - .venv/bin/tox run -e docs --notest
    - .venv/bin/tox run -e docs --skip-pkg-install --
