version: 2
build:
  image: latest
formats:
  - htmlzip
python:
   version: 3.8
   install:
      - method: pip
        path: .
        extra_requirements:
            - docs
sphinx:
  builder: html
  configuration: docs/conf.py
