version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3"
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
