class Overlapped:
    def __init__(self, event: int, /) -> None: ...
    def ReadFile(self, handle: int, size: int, /) -> None: ...  # noqa: N802
    def getresult(self, wait: bool | int = False, /) -> bytes: ...
